### PR TITLE
Update Liberty SPIs for release 23.0.0.3

### PR DESCRIPTION
**Pull request by pbalakrishnan-bts**

### CODE REVIEW

**Comment by pbalakrishnan-bts** [comment]
@BillyDawsonWork @BillyD73

**Comment by pbalakrishnan-bts** [comment]
Can we have someone review the PR?

**Comment by dbarfield** [comment]
Will leave this for Billy on Tuesday (national holiday here Monday) he's been on holiday this week.

**Comment by pbalakrishnan-bts** [comment]
@BillyD73 @dbarfield  is there something else i would need to do to have this version(23.0.0.3) listed in https://mvnrepository.com/artifact/net.wasdev.maven.tools.targets/liberty-target ?

**Comment by BillyD73** [comment]
There is a build process to upload to staging followed by Maven publication processes including WDT specific testing before we make the final push to live. 

Apologies, this is something we do as a post release task and we are in the middle of preparing our release targeted for the end of May. I will let you know as soon as we get the release out.

**Comment by pbalakrishnan-bts** [comment]
Thank you for the update! Really appreciate the prompt response. Eagerly waiting for this release(23.0.0.3)

**Comment by pbalakrishnan-bts** [comment]
@BillyD73 @dbarfield Any update on this?

**Comment by pbalakrishnan-bts** [comment]
@BillyD73 @dbarfield any info on when this is going to be released?

**Comment by mikeshepard04** [comment]
Hey @BillyD73 

Appreciate your response, and if we can get back to the regular quarterly releases that'd be great!

However, we would really like to get 23.0.0.3 going. Any chance we could we do this as a one-off build? We've got everything staged and ready to go for 23.0.0.3 so we're hoping to get this upgraded asap so we can complete our entire upgrade by the end of the year. If we have to go with 23.0.0.6 it'll just be a decent amount of extra work for one of our teams and may push us to a point where we have to wait until next year.

**Comment by BillyD73** [comment]
Hello,
We appreciate your request for updating SPIs for the release 23.0.0.3. We have discussed the possibility of doing the one-off build, but it poses more problems & risks due to the complexity and may even cause possible delays. Currently, we are working towards delivering this for 23.0.0.6. Are you going to be able to upgrade to Liberty 23.0.0.6 and use the updated SPIs for that instead? Can you confirm if you are using OL or WLP?

**Comment by mikeshepard04** [comment]
@BillyD73 was this published to Maven at the end of last month or are you still planning to do that? Right now I'm not seeing it out there.
https://mvnrepository.com/artifact/net.wasdev.maven.tools.targets/liberty-target

**Comment by pnickoll** [comment]
Hi @mikeshepard04 sorry about the delay - Billy has been out sick for a while - I've pushed 23.0.0.6 up here https://repo1.maven.org/maven2/net/wasdev/maven/tools/targets/liberty-target/23.0.0.6/

**Comment by mikeshepard04** [comment]
Hey @pnickoll. Appreciate you pushing that out! We were able to get upgraded to that version and everything is looking good 👍

**Comment by pnickoll** [comment]
@mikeshepard04 Excellent - we are hoping to push up 23.0.0.12 before too long too :)

**Comment by mikeshepard04** [comment]
No worries, appreciate the help and keeping those going! We'll be talking about another upgrade soon so that is great.

**Pull request merged**
